version: '2'
services:
  gateway:
    image: nginx
    volumes:
      - ./src/static/:/html/
      - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
    ports:
      - 80:80
    links:
      - gosrv

  rxmg:
    image: mongo
    ports:
      - 27017:27017

  gosrv:
    container_name: gosrv
    image: ntboes/golang-gin
    working_dir: /
    environment:
      - DB_NAME=stddev
      - DB_MONGO=rxmg
      - HOST=127.0.0.1:3001
    command:
      - -a
      - "3001"
      - run
      - main.go
    volumes:
      - ./src/go:/go/src/app/
      - ./src/static:/static
    ports:
      - 3000:3000
    links:
      - rxmg
